version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: solo-prj-server
    ports:
      - 27017:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo


  java-app:
    image: java-app
    ports:
      - 8080:8080
    environment:
    #      SPRING_DATA_MONGODB_USERNAME: root
    #      SPRING_DATA_MONGODB_PASSWORD: password
    #      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: db-prod
    depends_on:
      - mongo